### ISSUE TITLE
Dashboard Phone Numbers

### ISSUE THREAD

**Issue by maxCardo** [maxCardo/rethinkpm#12]
some numbers are only showing 9 numbers. first number looks like it cut off

**Comment by lagartoverde** [comment]
This is an inconsistency of the backend I think, on the dev db all the phone numbers are like this '14125954632', being the first number the country prefix.
I think on the production db some miss the first 1.
Do you think is worth it to include a condition so if they have only 10 numbers don't cut the first one? Or we should agree on a common data format for the phone numbers?

**Comment by lagartoverde** [comment]
Solution: Temporary bandaid for display on frontend
